### ISSUE TITLE
NK & KS flags

### ISSUE THREAD

**Issue by Galixte** [RMcGirr83/phpBB-3.1-nationalflags#10]
Hi @RMcGirr83,
- nk.png should be: https://github.com/RMcGirr83/phpBB-3.1-nationalflags/blob/master/flags/kp.png (source: https://en.wikipedia.org/wiki/ISO_3166-2:KP)
- ks.png should be: https://github.com/RMcGirr83/phpBB-3.1-nationalflags/blob/master/flags/kr.png (source: https://en.wikipedia.org/wiki/ISO_3166-2:KR)

**Comment by rmcgirr83** [comment]
Will be fixed soonish

**Comment by Galixte** [comment]
Merci.

**Comment by rmcgirr83** [comment]
Fixed

**Comment by Galixte** [comment]
Thanks. ;)
