### ISSUE TITLE
Warnings in ACP

### ISSUE THREAD

**Issue by pierrdu** [RMcGirr83/phpBB-3.1-nationalflags#14]
Hello,

Warnings in the ACP:
[phpBB Debug] PHP Warning: in file [ROOT]/ext/rmcgirr83/nationalflags/controller/admin_controller.php on line 567: Invalid argument supplied for foreach()
[phpBB Debug] PHP Warning: in file [ROOT]/ext/rmcgirr83/nationalflags/controller/admin_controller.php on line 571: array_multisort(): Argument #1 is expected to be an array or a sort flag
[phpBB Debug] PHP Warning: in file [ROOT]/ext/rmcgirr83/nationalflags/controller/admin_controller.php on line 573: implode(): Invalid arguments passed
Pierre Duhem

**Comment by rmcgirr83** [comment]
You aren't using the current from here.  This is line 567 in admin_controller file https://github.com/RMcGirr83/phpBB-3.1-nationalflags/blob/master/controller/admin_controller.php#L567 which is a comment.  Disable the extension, download all the files from here and overwrite those on your comp where you have this installed.  Re-enable the extension and try again.

**Comment by pierrdu** [comment]
Still the same thing, but the line numbers changed:
[phpBB Debug] PHP Warning: in file [ROOT]/ext/rmcgirr83/nationalflags/controller/admin_controller.php on line 573: Invalid argument supplied for foreach()
[phpBB Debug] PHP Warning: in file [ROOT]/ext/rmcgirr83/nationalflags/controller/admin_controller.php on line 577: array_multisort(): Argument #1 is expected to be an array or a sort flag
[phpBB Debug] PHP Warning: in file [ROOT]/ext/rmcgirr83/nationalflags/controller/admin_controller.php on line 579: implode(): Invalid arguments passed

**Comment by rmcgirr83** [comment]
Download newest admin controller which should fix that error.

**Comment by pierrdu** [comment]
I'll do it and let you know.
Thanks anyway for the good work.

**Comment by pierrdu** [comment]
It's ok.
Thanks for the good work.
