### ISSUE TITLE
Error Log (PHP Fatal error)

### ISSUE THREAD

**Issue by MixingOnBeat** [RMcGirr83/phpBB-3.1-nationalflags#17]
I have version 1.3.1 of this extension installed on my site. (The one that is offered at phpbb.com).  I haven't tried testing your latest commit changes or etc.

Just caught this error in my Error Logs for this extension:

`[20-Sep-2016 16:17:03 America/Toronto] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\InvalidParameterException' with message 'Parameter "flag_id" for route "rmcgirr83_nationalflags_getflags" must match "[^/]++" ("" given) to generate a corresponding URL.' in phpbb/vendor/symfony/routing/Symfony/Component/Routing/Generator/UrlGenerator.php:163
Stack trace:
#0 phpbb/vendor/symfony/routing/Symfony/Component/Routing/Generator/UrlGenerator.php(136): Symfony\Component\Routing\Generator\UrlGenerator->doGenerate(Array, Array, Array, Array, Array, 'rmcgirr83_natio...', false, Array)
#1 phpbb/phpbb/controller/helper.php(188): Symfony\Component\Routing\Generator\UrlGenerator->generate('rmcgirr83_natio...', Array, false)
#2 phpbb/ext/rmcgirr83/nationalflags/event/listener.php(366): phpbb\controller\helper->route('rmcgirr83_natio...', Array)
#3 [internal function]: rmcgirr83\nationalflags\event\listener->viewtopic_modify_pos in phpbb/vendor/symfony/routing/Symfony/Component/Routing/Generator/UrlGenerator.php on line 163`

**Comment by rmcgirr83** [comment]
You allow guest posting or have removed a user from a post?  Not sure how the system thinks what is being returned is a string instead of an integer.  Try uploading a fresh listener file and purging the cache.
