### ISSUE TITLE
problem with 3.2

### ISSUE THREAD

**Issue by costanzomoffa** [RMcGirr83/phpBB-3.1-nationalflags#18]
hi i have this message on 3.2 

Fatal error: Can't use method return value in write context in /home2/costanzo/public_html/ext/rmcgirr83/nationalflags/controller/admin_controller.php on line 587

**Comment by rmcgirr83** [comment]
What version of PHP?

**Comment by rmcgirr83** [comment]
https://github.com/rmcgirr83/phpBB-3.1-nationalflags/commit/28aac44b5598425bad4a8c8f99bb117706baf2a2

**Comment by costanzomoffa** [comment]
5.4

**Comment by rmcgirr83** [comment]
You can either update your PHP version to > 5.4 or apply these edits https://github.com/rmcgirr83/phpBB-3.1-nationalflags/commit/28aac44b5598425bad4a8c8f99bb117706baf2a2
