### ISSUE TITLE
L’extension sélectionnée ne peut pas être activée. Veuillez en vérifier les prérequis.

### ISSUE THREAD

**Issue by Owned67** [RMcGirr83/phpBB-3.1-nationalflags#19]
Hello,

php 5.6
phpbb 3.2.0

why i get this error when active this extension ?

Thanks

**Comment by rmcgirr83** [comment]
I don't speak nor read french

**Comment by Owned67** [comment]
In english: The selected extension is not available for this board, please verify your phpBB and PHP versions are allowed (see the details page)

**Comment by rmcgirr83** [comment]
https://github.com/rmcgirr83/phpBB-3.1-nationalflags/releases/tag/3.2
