### ISSUE TITLE
Missing Ex-Yugoslavian countries.

### ISSUE THREAD

**Issue by Kame03** [RMcGirr83/phpBB-3.1-nationalflags#26]
I've noticed that Serbia is missing on forums that use this extension, Macedonia being an exception, I cannot find Serbia, Montenegro, Croatia, Bosnia and Herzegovina. 

![image-1](https://github.com/user-attachments/assets/c5070690-cf12-4440-a40c-765a8a01ce6d)

![main-qimg-98514600a646b912b6b6be76822fa705](https://github.com/user-attachments/assets/90200953-8571-450a-b952-87af8c89fbd9)

**Comment by rmcgirr83** [comment]
The extension allows you to add flags that are missing....so add them. I've added 200+ to alleviate others having to add all the flags of countries but, obviously, couldn't be expected to add every single country.

**Comment by Kame03** [comment]
There are only 195~ countries in the world, not 200+ so this doesn't make sense that much, also Ex-Yugoslavian countries are in Europe so it doesn't make sense not having them but having the rest, when the whole point of this extension is to have national flags, and it shouldn't be hard to add countries whenever someone asks for it in a github issue, considering that I do not own or operate the phpBB forums utilizing your extension so telling me to add the countries myself is not possible.  And if this is a requirement then there shouldn't be any countries added whatsoever so that the users of the extension can just add them on their own. 

On August 5, 2024 1:55:30 AM GMT+02:00, Rich McGirr ***@***.***> wrote:
>The extension allows you to add flags that are missing....so add them. I've added 200+ to alleviate others having to add all the flags of countries but, obviously, couldn't be expected to add every single country.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/rmcgirr83/nationalflags/issues/26#issuecomment-2267949646
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
Viktor M

**Comment by Kame03** [comment]
And I believe that most owners of their phoBB boards that installed this extension believe that there are all the countries covered here, as confirmed by me asking them to add them manually upon your response, they aren't aware of that, while another board owner was the one directing me to this github page to ask you to add my country on the list, which is why I did it in the first place. Anyways if you don't want to add them, I would like to add them myself and do a pull request if you tell me how exactly would I go about doing this properly.

On August 5, 2024 4:51:43 AM GMT+02:00, "Viktor Milivojević" ***@***.***> wrote:
>There are only 195~ countries in the world, not 200+ so this doesn't make sense that much, also Ex-Yugoslavian countries are in Europe so it doesn't make sense not having them but having the rest, when the whole point of this extension is to have national flags, and it shouldn't be hard to add countries whenever someone asks for it in a github issue, considering that I do not own or operate the phpBB forums utilizing your extension so telling me to add the countries myself is not possible.  And if this is a requirement then there shouldn't be any countries added whatsoever so that the users of the extension can just add them on their own. 
>
>On August 5, 2024 1:55:30 AM GMT+02:00, Rich McGirr ***@***.***> wrote:
>>The extension allows you to add flags that are missing....so add them. I've added 200+ to alleviate others having to add all the flags of countries but, obviously, couldn't be expected to add every single country.
>>
>>-- 
>>Reply to this email directly or view it on GitHub:
>>https://github.com/rmcgirr83/nationalflags/issues/26#issuecomment-2267949646
>>You are receiving this because you authored the thread.
>>
>>Message ID: ***@***.***>
>Viktor M
Viktor M

**Comment by rmcgirr83** [comment]
The number of countries in the world is not as cut and dry as what the UN says are de facto countries. The UN recognizes 193 as countries while the US CIA fact book lists 230+ and Britannica also lists more than 193. There are countries and there are also sovereign states. 
To make the pull request, you would have to clone the repo, add the flag to the flags directory and [create a migration file](migrations/m4_add_data.php) to get the flag into the database.
The board owner who directed you to here could quite easily add the missing country.

**Comment by Kame03** [comment]
> The number of countries in the world is not as cut and dry as what the UN says are de facto countries. The UN recognizes 193 as countries while the US CIA fact book lists 230+ and Britannica also lists more than 193. There are countries and there are also sovereign states. To make the pull request, you would have to clone the repo, add the flag to the flags directory and [create a migration file](migrations/m4_add_data.php) to get the flag into the database. The board owner who directed you to here could quite easily add the missing country.

The link you sent for the migration file is not working.
![image](https://github.com/user-attachments/assets/84df5799-83ba-4cdb-ad92-90771f4a831f)

However I did find the file you're referring to here: https://github.com/rmcgirr83/nationalflags/blob/master/migrations/m4_add_data.php
Does it matter where the country is located in that file, does it need to follow certain alphabetical order, or just needs to be a valid PHP with the country name pointing to the flag image?

**Comment by rmcgirr83** [comment]
FWIW I just looked and both Croatia (hr) and Boznia (ba) are in the lang files as well as database migration files and they are both selectable on my test forum.
