### ISSUE TITLE
Correct spelling of flag name to Colombia, from incorrect of Columbia

### ISSUE THREAD

**Issue by lindakanga** [RMcGirr83/phpBB-3.1-nationalflags#28]
The country name is Col**o**mbia,  
and not Col**u**mbia, with a **u**.  

Being for the Flag image of ![image](https://github.com/user-attachments/assets/450c149a-28f0-4bb7-b119-2715e4bafc74)

i.e. refer to :
Government site : https://www.cancilleria.gov.co/en/visit-colombia  
https://en.wikipedia.org/wiki/Colombia
https://www.thoughtco.com/how-did-colon-become-columbus-3079508

Thank you for this very useful app that is appreciated by our volunteer language learning community.

**Comment by rmcgirr83** [comment]
Minutia, the admin of the forum can change the name of the flag in the ACP as well as in whichever language file if necessary.
