### ISSUE TITLE
how to add the flag to the viewtopic and other parts of the forum

### ISSUE THREAD

**Issue by wullien** [RMcGirr83/phpBB-3.1-nationalflags#9]
how would i go about adding the flags to a custom style like the pics i got it on the index page but it wont show on posts
![hfoyufoyuf](https://cloud.githubusercontent.com/assets/13025078/8319606/a1add540-1a08-11e5-8280-d907603d2bb7.jpg)

**Comment by rmcgirr83** [comment]
Means you are missing events in that style.

**Comment by wullien** [comment]
What would I have to edit in order to get it on to the page if you could help

**Comment by rmcgirr83** [comment]
Impossible to say as you don't provide any files namely viewtopic_body.html
